#title in header
title: "Aobzii"

#main info
#owner
owner: "Aobzii"
info: "A blog about notes, daily fragments, and rambles."
#description
desc: "Lost tea egg, found in writing."

#menu
menu:
  Daily: /daily/
  Archive: /archives/
  About: /about/

#index/main page max show posts (in number)
max_post: 5

# Colors use hex color without #
# Theme color
tcolor: 8FCF9D

# Define path to user css
#(could be also located outside of theme)
# Relative to source/ directory
usercss: css/user.css

# social profile at the footer/bottom
footer: true
github: https://github.com/Aobzii2024
outlook: mailto:aobzii2024@outlook.com
netease_music: https://music.163.com/#/user/home?id=3669845181
telegram: https://t.me/+wa2hX3Kax9BkNTVh

# Misc
nanobar: /js/nanobar.min.js
switch_light: ☀️
switch_dark: 🌑

# Picture enlargement
picjs: /js/pic.min.js

# favicon
favicon: /images/main.jpg
# thumbnail
thumbnail: /images/main.jpg

article:
  thumbnail: true
